#!/bin/bash

for range in {60..89}; do
    for ((i=$range; i<=$range; i++)); do
        ./run -u Cmdenv -c BreakRanksNoGui -r $i
        #python3 ~/src/plexe/bin/findCollisions.py --glob "/home/bertuzzi/src/plexe/examples/platooning/*collisions.xml" #> results_run_$i.txt
    done
done

# {80..119} {320..359} {560..599} {800..839}

# for ((i=80; i<=119; i++)); do
#     ./run -u Cmdenv -c BreakRanksNoGui -r $i
#     python3 ~/src/plexe/bin/findCollisions.py --glob "/home/bertuzzi/src/plexe/examples/platooning/*collisions.xml" > results_run_$i.txt
# done
