#!/bin/bash

for ((i=20; i<=29; i++)); do
    ./run -u Cmdenv -c BreakRanksNoGui -r $i
    python3 ~/src/plexe/bin/findCollisions.py --glob "/home/bertuzzi/src/plexe/examples/platooning/*collisions.xml" > results_run_$i.txt
done
