#!/bin/bash

for range in {20..29}; do
    for ((i=$range; i<=$range; i++)); do
        ./run -u Cmdenv -c BreakRanksNoGui -r $i
        #python3 ~/src/plexe/bin/findCollisions.py --glob "/home/bertuzzi/src/plexe/examples/platooning/*collisions.xml" #> results_run_$i.txt
    done
done

# {80..119} {320..359} {560..599} {800..839}
#{40..59} {160..179} {280..299} {400..419}
#{520..539} {640..659} {760..779} {880..899} {1000..1019} {1120..1139} {1240..1259} {1360..1379} {1480..1499} {1600..1619} {1720..1739} {1840..1859}

# for ((i=80; i<=119; i++)); do
#     ./run -u Cmdenv -c BreakRanksNoGui -r $i
#     python3 ~/src/plexe/bin/findCollisions.py --glob "/home/bertuzzi/src/plexe/examples/platooning/*collisions.xml" > results_run_$i.txt
# done
